# the _config.yml of lemon-lime
# ==== Nav link====
nav:
  Home: /
  Archives: /archives
  Tags: /tags #extra work needed for this to work
  Catogories: /categories #extra work needed for this to work
# ==== site logo ====
favicon: '/compass/imgs/favicon.ico' #the default favicon, feel free to change


# ==== Table of Content ====
toc:
  list_number_on: false  #if this is set to 'true', headings of your posts should not have numerical ordered added manually. 

# ==== Copyright ====
copyright_on: true
copyright:
  liscense_type: CC BY-NC-SA 4.0
  liscense_link: http://creativecommons.org/licenses/by-nc-sa/4.0/

# ==== Footer Setting ====
inception: 2017 # feel free to change
hexo_link: http://hexo.io
email_address:
social_media:
  github:
    name: github
    address: https://github.com/ClareChu # replace this link with yours
    icon: fa-github
  weibo:
    name: weibo
    address: # add your link here, like the way you do with github's address or just ignore it
    icon: fa-weibo
  facebook:
    name: facebook
    address: # add your link here, like the way you do with github's address or just ignore it
    icon: fa-facebook
  twitter:
    name: twitter
    address: # add your link here, like the way you do with github's address or just ignore it
    icon: fa-twitter

# ==== Additional Setting ====
# View Count by busuanzi
busuanzi_on: true # set to false to disable the view count for your site and posts

# Algolia Search
algolia_on: false # set to true to enable seach within your site, note that extra work needed
algolia:
  applicationID:
  apiKey:
  indexName:
  chunkSize: 5000
  field:
    - title
    - path
    - excerpt:strip
    - excerpt

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: lemon-lime

deploy:
  type: git
  repo: https://github.com/ClareChu/clarechu.github.io
  branch: themes
  message: "init"