apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: mysql-server
  name: mysql-server
  namespace: demo1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-server
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: mysql
          imagePullPolicy: Always
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-server
  name: mysql-server
  namespace: demo1
spec:
  clusterIP: 10.68.228.107
  externalTrafficPolicy: Cluster
  ports:
    - name: 3306-3306
      nodePort: 32011
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-server
  sessionAffinity: None
  type: NodePort